api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        pagination_items_per_page: 6
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
